version: '3'

services:
  # A P I  G A T E W A Y
  api-gateway:
    build:
      context: './api-gateway'
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-gateway:/opt/app
      - /opt/app/node_modules
    depends_on:
      - characters-service
      - players-service
    ports:
      - 7000:7000
  # C H A R A C T E R S
  characters-service:
    build:
      context: './characters-service'
      dockerfile: Dockerfile.dev
    volumes:
      - ./characters-service:/opt/app
      - /opt/app/node_modules
    depends_on:
      - characters-service-db
    environment:
      - MONGO_URI=mongodb://mongo:27017/smash
    ports:
      - 7100:7100
  # M O N G O - D B
  characters-service-db:
    container_name: mongo
    image: mongo
    ports:
      - 0.0.0.0:7200:27017
    logging:
      driver: 'none'

  # P L A Y E R S
  players-service:
    build:
      context: './players-service'
      dockerfile: Dockerfile.dev
    depends_on:
      - players-service-db
    environment:
      - DB_URI=postgres://user:password@players-service-db/db?charset=UTF8
    volumes:
      - ./players-service:/opt/app
      - /opt/app/node_modules
    ports:
      - 7101:7101
  # P O S T G R E S Q L- D B
  players-service-db:
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    image: postgres
    ports:
      - 0.0.0.0:7201:5432
    logging:
      driver: 'none'
