version: 2.1
jobs:
  build:
    working_directory: ~/repo/players-service
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run: npm install
          - run: npm test
